version: "3.8"

services: 
    sokemotor:
        build:
            context: .
        container_name: sokemotor
        hostname: sokemotor

        depends_on: 
            - elastic

        networks: 
            - soke-elastic
        ports: 
            - 8080:8080
        
        working_dir: /app

        volumes: 
            - ./:/app
            - $GOPATH:/go/

    elastic:
        image: elasticsearch:7.13.4

        environment: 
            - discovery.type=single-node

        container_name: elastic
        hostname: elastic
        volumes: 
            - elastic-data:/usr/share/elasticsearch/data
        networks: 
            - soke-elastic     
networks:
    soke-elastic:
        driver: bridge

volumes: 
    elastic-data:
